@startuml
'https://plantuml.com/class-diagram

class WarehouseActionUI{
}

class WarehouseActionController{
+ createUS306()
}


class US306 {
- initialize()
+ toString()
}

class WriteForAFile{
+ writeForAFiLe(textualInformation)
}


WarehouseActionUI ..> WarehouseActionController
WarehouseActionController -> US306
US306 --> WriteForAFile : uses

@enduml