@startuml
autonumber

actor "Traffic manager" as manager
participant "System" as system
activate manager

manager -> system ++: Import ships from a text file into a BST

system --> manager --: Requests the name of the .csv file\n containing the data

manager -> system ++: Inserts file name

system --> manager --: Displays the number of ships which have not been imported


@enduml