@startuml

autonumber
actor "Traffic Manager" as manager

participant ":ImportShipUI" as ui
participant ":ImportShipController" as controller
participant ":ImportShip" as importShip
participant "shipLocation:ShipLocation" as shipLocation
participant "ship:Ship" as ship


activate manager
manager -> ui : import ships from a text file into a BST


activate ui
ui --> manager : requests the name of the .csv file containing the data


deactivate ui


manager -> ui : inserts file name


activate ui


ui -> controller : importFile(fileName)
activate controller


controller -> importShip : getFile(fileName)
activate importShip


deactivate importShip
deactivate controller


ui -> controller : importShips()
activate controller


controller -> importShip : shipsNotConverted = convertShips()
activate importShip


loop for each line on the file


importShip -> importShip ++: shipArray = getLineArray(shipLine)
deactivate importShip


importShip -> importShip ++: shipsNotConverted = createShip(shipArray)


create shipLocation
importShip --> shipLocation: create(messageTime, latitude, longitude, SOG, COG,\n heading, position, transceiverClass)

importShip -> company : shipBST = getBstShip()
activate company
deactivate company

importShip -> shipBST : newShip = getShipByMmsiCode(MMSI)
activate shipBST
deactivate shipBST

alt newShip does not exist in the Company Ship Tree (shipBST)

create ship
importShip --> ship: create(MMSI, name, shipID, energyGenerators, generatorOutput,\n callSign, vesselType, length, width, capacity, draft, shipLocation)


participant ":Company" as company
participant "shipBST:ShipBST" as shipBST


importShip -> shipBST : insert(ship)
activate shipBST
deactivate shipBST

else Ship exists in the Company Ship Tree

participant "shipLocationBST : ShipLocationBST" as shipLocationBST

importShip -> ship : shipLocationBST = getShipPosition()
activate ship
deactivate ship

importShip -> shipLocationBST : insert(shipLocation)
activate shipLocationBST
deactivate shipLocationBST

deactivate importShip
end


importShip --> controller : shipsNotConverted
deactivate importShip

controller --> ui : shipsNotConverted
deactivate controller

ui -> manager : Displays the number of ships which have not been imported


@enduml

