@startuml
'https://plantuml.com/class-diagram

class KnowRouteUI{
}

class KnowRouteController{
+ createUS205(registrationCode, containerId)
}


class US305 {
- initialize(registrationCode, containerId)
+ toString()

}

class WriteForAFile{
+ writeForAFiLe(textualInformation)

}


KnowRouteUI ..> KnowRouteController
KnowRouteController -> US305
US305 --> WriteForAFile : uses

@enduml