@startuml
'https://plantuml.com/class-diagram

class FindClosestPortUI {}

class FindClosestPortController {
-findClosestPort(callSign, date)

}

class Company {
-designation
-getBstShip()
-getPortStr()
}

class BstShip {
-getShipByCallSign(callSign)
}

class Ship {
-getShipPosition()
}

class ShipLocationBST {
-getShipLocation(date)
}

class ShipLocation {

}

class Ports {

}


class PortStore {
-getPorts2DTree()
}

class Ports2DTree {
-findNearestNeighbour(latitude, longitude)
}

class PortsMapper {
-toDto(port)
}

class PortsDto {
}

Company "1"--"1..*" Ports: have >
Company "1"--"1..*" Ship: own >

Ship "0..*"--"1" Ports: dock >
Ship "1" -- "1..*" ShipLocation : has >

Ports "1" -- "1" PlaceLocation : located at >

FindClosestPortUI ..> FindClosestPortController
FindClosestPortController ..> Company
FindClosestPortController ..> BstShip
FindClosestPortController ..> Ship
FindClosestPortController ..> ShipLocationBST
FindClosestPortController ..> PortStore
FindClosestPortController ..> Ports2DTree
FindClosestPortController ..> PortsMapper
PortsMapper ..> PortsDto
PortStore "1"--> "*" Ports : adopts


@enduml