@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Employee {
-name
}

class Ports {
-identification
-name
}

class PlaceLocation {
-latitude
-longitude
}

class Country {
-name
-continent
}

class Company {
-designation
}

class Ship {
-mmsiCode
-imoCode
-numberEnergyGenerators
-generatorPower
-callSign
-draft
-name
-vesselTypeId
-length
-width
-capacity
}

class ShipLocation {
-baseDateTime
-latitude
-longitude
-sog
-cog
-heading
-position
-transceiver
}

Company "1"--"1..*" Ship: own >
Company "1"--"1..*" Employee: have >
Company "1"--"1..*" Ports: have >
Employee "1" --- "1..*" Ports : controls >
Ship "0..*"--"1" Ports: dock >
Ship "1" -- "1..*" ShipLocation : has >

Ports "1" -- "1" PlaceLocation : located at >
PlaceLocation "*" -- "1" Country : placed in >
@enduml