@startuml
'https://plantuml.com/sequence-diagram

actor "Fleet Manager" as FM
participant ":405UI" as UI


activate FM
FM -> UI : requests to know the average occupancy rate per manifest of a given ship during a given period
activate UI
UI --> FM : asks to enter period to analyze (initialTime, endTime)
deactivate UI
FM -> UI : inserts the requested data (initialTime, endTime)
activate UI

UI --> FM : receive the result
deactivate UI
deactivate FM
@enduml