typedef struct { //cMContainer struct
    int containerId;                       
    int x;
    int y;
    int z;
    char isRefrigerated;
    int isoCode;
    float grossContainer;
    float maxWeight;
    float weight;
    float tare;
    float maxVolume;
    float outerThickness;
    float middleThickness;
    float innerThickness;
    float outerCapacity;
    float middleCapacity;
    float innerCapacity;
} cMContainer;