@startuml
'https://plantuml.com/class-diagram
actor "Ship Captain" as SC
participant "System" as SY

activate SC
SC -> SY : starts the requisition of the list \n of containers to be unloaded in the next port
activate SY
SY --> SC : asks the mmsi code of the ship
deactivate SY
SC -> SY : type the mmsi code

activate SY
SY-->SC : show the result
deactivate SY
deactivate SC
@enduml