@startuml
'https://plantuml.com/class-diagram

hide methods

skinparam classAttributeIconSize 0

class Employee {
-name
}

class Ports {
-identification
-name
}

class PlaceLocation {
-latitude
-longitude
}

class Country {
-name
-continent
}

class Company {
-designation
}

Company "1"--"1..*" Employee: have >
Company "1"--"1..*" Ports: have >
Employee "1" --- "1..*" Ports : controls >


Ports "1" -- "1" PlaceLocation : located at >
PlaceLocation "*" -- "1" Country : placed in >
@enduml