@startuml
'https://plantuml.com/sequence-diagram
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Ship {
-mmsiCode
-imoCode
-numberEnergyGenerators
-generatorPower
-callSign
-draft
-name
-vesselTypeId
-length
-width
-capacity
}

class Containers {
-x
-y
-z
-containerNumber
-checkDigit
-isoCode
-payLoad
-tare
-gross
-weight
}

class CargoManifest {
-listOfContainers
-ratio
-date
-mmsiCode
-id
-numberOfContainers
-destination
}

Containers "1..*"--"1..*" CargoManifest: related to >
Ship "1"---"1..*" Containers : transport >
@enduml