@startuml
'https://plantuml.com/class-diagram
actor "Ship Captain" as SC
participant "System" as SY

activate SC
SC -> SY : starts the requisition of mean container \n per cargo manifest and the total number \nof cargo manifest per year
activate SY
SY --> SC : asks the mmsi code of the ship
deactivate SY
SC -> SY : type the mmsi code
activate SY
SY --> SC : ask the year of the cargo manifest
deactivate SY
SC->SY : type the year
activate SY
SY-->SC : show the result
deactivate SY
deactivate SC
@enduml