@startuml
'https://plantuml.com/sequence-diagram
actor "Ship Captain " as SC
participant ": ShipCaptainUI" as UI

activate SC
SC -> UI : requests to know for a specific vessel, how much \ndid the vessel sink, assuming that each container\n has half a ton of mass
activate UI
UI --> SC : shows requested information
deactivate UI
deactivate SC

@enduml