@startuml
'https://plantuml.com/sequence-diagram

actor "Traffic Manager" as TM
participant ":US309UI" as UI
participant ":US309Controller" as CT

participant ":US309Handler" as US
participant ":WriteForAFile" as WF

activate TM
TM -> UI : Orders to not allow a cargo manifest \nfor a particular ship  to be registered \n in the system on a date when the \n ship is already occupied.
activate UI


UI->CT : createUS309()

activate CT
CT -> US** : create()
US -> US : initialize()
activate US
US->US : textualInformation = toString()
activate US
deactivate US
US -> WF : writeForAFile(textualInformation)
activate WF
deactivate WF

deactivate US




UI --> TM : receive or not a warning
deactivate UI
deactivate TM
@enduml